### ISSUE TITLE
Hairnet in Blender 2.8 doesn't work

### ISSUE THREAD

**Issue by rovh** [Jandals/HairNet#10]
![Снимок экрана (1)](https://user-images.githubusercontent.com/56371012/66526535-c25ed400-eb01-11e9-860f-8e32ca5db977.png)
My steps:
1)I select curve
2)select sphere
3)click "add hair from curves" in N-panel
After that i get an error, and sphere gets particle system.

**Comment by DragonHawkAlpha** [comment]
Does not work for me either.

**Comment by Jandals** [comment]
Thanks for reporting this.
That line
sel.select = True

didn't get updated. It needs to say 
sel.select_set(state=True)

I'll post the correction shortly.
If you try to make hair from a curve object that has more than one curve segment in it, you'll get an error. In that case, converting the curves into a mesh lets you use the "Make hair from fibers" button and should give you a result identical to using curve objects.

Just be aware that the "Convert to" command in Blender doesn't make a copy of your curves. You'll have to make a copy yourself.

**Comment by rovh** [comment]
I tryed to  make hair from a curve object that has more than one curve segment in it, but i didn't get a bug. Also i tryed to use two objects and  i didn't get a bug. But when i used two object for making hair i got new bug(I had alredy written about it in another issue)
![Снимок экрана (6)](https://user-images.githubusercontent.com/56371012/66719503-7c538a00-edf9-11e9-9858-8a9d2f1ea1ac.png)
