### ISSUE TITLE
doesnt work in 2.91.0 but works 2.90.1

### ISSUE THREAD

**Issue by yourherobby** [Jandals/HairNet#22]
when i click fibermes with self emit selected like in tutorial

Python: Traceback (most recent call last):
  File "C:\Users\DESKTOP\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 612, in invoke
    return self.execute(context)
  File "C:\Users\DESKTOP\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 583, in execute
    self.createHair(targetObject, hairGuides, options)
  File "C:\Users\DESKTOP\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 685, in createHair
    bpy.ops.particle.brush_edit(stroke=[{'name': '', 'location': (0, 0, 0), 'mouse': (0, 0), 'pressure': 0, 'size': 0, 'pen_flip': False, 'time': 0, 'is_start': False}])
  File "D:\_blender\blender-2.91.0-windows64\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties:  PARTICLE_OT_brush_edit.stroke error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "mouse_event" missing

location: <unknown location>:-1

**Comment by tamamo-no-ame** [comment]
Getting this error as well.

I am trying to come up with content that illustrates the problem, but isn't several megabytes in size.

`Report: Error
! Python: Traceback(most recent call last):
	File"C:\Users\Kryslin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 612 in invoke
		return self.execute(context)
	File"C:\Users\Kryslin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 583 in execute
		self.createHairTarget(targetObject, hairGuides, options)
	File"C:\Users\Kryslin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\hairNet\hairNet.py", line 685 in createHair
		bpy.ops.particle.brush_edit(stroke=[{'name': '', 'location': (0, 0, 0), 'mouse': (0, 0), 'pressure': 0, 'size': 0, 'pen_flip': False, 'time': 0, 'is_start': False}])
	File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\bpy\ops.py", line 132, in __call__
		ret = _op_call(self.idname_py(), None, kw)
		
	TypeError:  Converting pyargs to operator properties: PARTICLE_OT_brush_edit.stroke error converting a member of a collection from a dicts into an RNA collection, failed with: TypeError: Converting a Python list to an RNA collection: keyword "mouse_event" missing.
	`
Blender 2.90.1, Blender 2.91, Blender 2.92alpha.

**Comment by Jandals** [comment]
I think this has been fixed. I'll update soon.

**Comment by comicsserg** [comment]
I have the same issue on 2.91

**Comment by Jandals** [comment]
Version 0.6.3 should be working in Blender 2.91 now.
https://github.com/Jandals/HairNet/releases/tag/v0.6.3
