### ISSUE TITLE
Traceback error and installation issues

### ISSUE THREAD

**Issue by Nico3u** [Jandals/HairNet#27]
![HairnetIssue](https://user-images.githubusercontent.com/81316077/112351849-881fcd00-8cca-11eb-8397-9b663d365fb7.png)
![InstallationIssue](https://user-images.githubusercontent.com/81316077/112351855-8950fa00-8cca-11eb-8eea-b5184d9a9c47.png)
Hello there, 
I tried to use this Add-on in Blender 2.90.1 but it never worked, it always came up with a traceback error. 
In order to try the latest version of your add-on, i uninstalled Blender 2.90.1 and updated to **2.91**.
When I tried to re install the add-on (vers **0.6.3**), it came up with an error about multiple add-ons with the same name, even if the add-on shows up in my tools menu. When I try to use it, it comes up with the traceback error as it did in Blender 2.90.1. 

As it is shown in the screenshot i took, I selected the curve first and the hair emitter mesh second. The curve has no bevels.
Thank you if you will help me :3 and forgive my english, it is not as good as it should be.

**Comment by Jandals** [comment]
I can't tell for sure, because the second line of that second error is clipped off, but it does look like there's an old version of the add-on installed.

I think the simplest solution is to delete the scripts\addons\hairNet folder written in the message and re-install hairNet. That should give you one installed version which has been updated to work the way you expect it to.

**Comment by Nico3u** [comment]
I deleted all the folders about HairNet and tried to re-install it, but I guess I'm messing up something. I only downloaded the hairnet.zip folder in 0.6.3 release, once installed on Blender it gave me the same error of multiple same name add-ons it gave me before. Which folder do I have to download to get it without duplicates?

**Comment by Jandals** [comment]
It's very strange that deleting the existing HairNet folders didn't help. Something must have been missed. I just re-installed my add-on using the 0.6.3 ZIP file and it went fine. So that download file should be ok.

The "multiple add-ons" message that Blender shows you in the preferences window will tell you where the two problem add-ons are. I can't see from the posted picture what the complete paths are but you can make that window bigger and see the whole paths.

**Comment by Nico3u** [comment]
Here there is the complete message, sorry for cutting it off in the first message. I can still enable the add-on even if this problem exists, but I will get the traceback error. I got that error even when I first installed it, about a week ago, when I had no installation issues. 
Thank you for your time man 

![InstallationIssue2](https://user-images.githubusercontent.com/81316077/112748445-e8a95580-8fbb-11eb-818c-14b5185d32a6.png)

**Comment by Jandals** [comment]
Now I can see that "hairNet.py" is installed. That's the old version of the addon. That's what Blender is trying to use, which is probably why it's not working.

If you follow that filepath and delete hairNet.py, which is in the addons folder itself, it should start working better.

**Comment by Nico3u** [comment]
Ok I found out that some datas leftover in my C:, so after a deeper research I deleted everything about hairNet and reinstalled the 0.6.3 folder, so now the installation issue is solved. 
Back to the traceback error, I'll post some new screenshots I took.
As you can see, some of the curves seem to work, but they emit hair in the wrong position, while some others curves give me the traceback error. 
I'll also post a screenshot of the curves geometry, cause it seems "doubled" (made of 2 different curves) and I thought that could be probably be an issue for the add-on.

![Error_1](https://user-images.githubusercontent.com/81316077/112832848-30041480-9096-11eb-8bec-fa5bd3db77c6.png)
![Error_2](https://user-images.githubusercontent.com/81316077/112832851-309cab00-9096-11eb-9f1a-d4657b96674d.png)
![Error_3](https://user-images.githubusercontent.com/81316077/112832852-31354180-9096-11eb-8d34-87ae2889ebda.png)
![Braid_Geometry](https://user-images.githubusercontent.com/81316077/112832854-31cdd800-9096-11eb-9b6c-9cc60c9049cd.png)

**Comment by Jandals** [comment]
Thanks for the new information. I can see that a few things aren't working right but they don't account for the traceback error you're seeing.

I can't reproduce the error you're seeing so there may be a part which is unique to something you've made. Are you willing to share this blend file with me so I can sort out where it's going wrong?

In the meantime, I added an update to hairNet today. It may be worth installing it in case it clears up the traceback error. It should install over the existing version without having to go and delete any old files.
https://github.com/Jandals/HairNet/releases/tag/v0.6.4

**Comment by Nico3u** [comment]
Hey man,
I tried the update you said, no installation issues this time but I can't see the HairNet window in the menu tools anymore, lol.
Anyway, I can't send the file here cause it only allows me to share pics or pdf or whatever, so I'll need your e-mail for this.
Thank you

**Comment by Jandals** [comment]
I also had the window disappear after an update. I fixed it by going to the add-on preferences window, then unchecking and re-checking hairNet. That brought it right back for me; maybe that would work for you, too.

You can send me an email at le_chuga@mac.com

**Comment by Nico3u** [comment]
Done, I had to sent it as a Google Drive link

**Comment by Jandals** [comment]
One of the viewport "overlays" is called "Statistics" and it lets you see how many control points you have selected. That would help with getting curves to have the same number of points.

For the position and rotation, you'll need to apply the location and rotation you've put on your models so they all have the same origin point. This is something I keep fixing but then it changes within Blender again…

I'm sorry for all the hang-ups. I've got some updating to do…

**Comment by Nico3u** [comment]
Yasssssssssssssssssssssssss it finally worked
Thank you for your assistance man, very kind of you 

![Immagine](https://user-images.githubusercontent.com/81316077/113290716-545c2d00-92f2-11eb-93e9-f7069560f0af.png)
