### ISSUE TITLE
Can't enable hairnet after installation

### ISSUE THREAD

**Issue by hartigraph** [Jandals/HairNet#28]
![Screenshot_41](https://user-images.githubusercontent.com/80718736/115086614-384fb280-9ed2-11eb-81d9-e0cb20bc786a.png)
I installed fine, but get this error every time I try to tick it on

**Comment by kex0** [comment]
Same

**Comment by Jandals** [comment]
Ugh... I forgot to take care of that line. I should be able to fix that tonight. Sorry about that.

**Comment by hartigraph** [comment]
No problem! Thanks for the quick response

**Comment by Jandals** [comment]
Things should be back to normal again.

https://github.com/Jandals/HairNet/releases/tag/v0.6.5

**Comment by hartigraph** [comment]
Hm, now I'm getting this 
![Screenshot_33](https://user-images.githubusercontent.com/80718736/115128092-ff324380-9fa0-11eb-89c4-29444344907a.png)

**Comment by Jandals** [comment]
Whoops! That's because I left out a file. Sorry.

I've updated the zip file for the 0.6.5 release.

https://github.com/Jandals/HairNet/releases/tag/v0.6.5

**Comment by hartigraph** [comment]
Installed fine now. Thanks!
