### ISSUE TITLE
Use it in blender 2.8

### ISSUE THREAD

**Issue by NaughtDZ** [Jandals/HairNet#3]
I can't use this plug-in in version 2.8. Are there plans to update the plug-in in version 2.8 in the future?

**Comment by Jandals** [comment]
There's a bug in Blender 2.8 that keep HairNet from working. When that gets fixed, I'll be able to update HairNet.

**Comment by juangea** [comment]
jey @Jandals whats the bug? (in developer.blender.org I mean)

**Comment by Jandals** [comment]
https://developer.blender.org/T65624
