### ISSUE TITLE
Hair steps very limited on Eevee

### ISSUE THREAD

**Issue by hortiSquash** [Jandals/HairNet#32]
![image](https://user-images.githubusercontent.com/45213805/117720863-7abd9400-b1df-11eb-9f05-7a753867cfb6.png)
Eevee VS Cycles

You can increase the setting Hair Additional Subdiv in Eevee parameters to be smoother (as done in the bottom example) but it doesnt quite follow the initial curve, especially in tight turns or complex and longer paths

Not sure if that is an Eevee engine limitation but that is definitely something to be aware of. And its even more limited in the viewport

**Comment by Jandals** [comment]
There are settings in Particle Properties, too, that affect the curve subdivisions. Viewport Display -> Strand Steps. As far as I can see, this is all Cycles, Eevee, and particle settings, and not anything in HairNet itself.
