### ISSUE TITLE
TypeError: Converting py args to operator properties

### ISSUE THREAD

**Issue by meso1** [Jandals/HairNet#34]

**Comment by meso1** [comment]
This error occurs after executing the command from sheets to hair particles.

![USqZiI8EIB](https://user-images.githubusercontent.com/85611790/121319808-88ce1400-c947-11eb-9bf1-2129018722b2.png)

**Comment by Jandals** [comment]
It looks like you're using an old version of HairNet, but not old enough. That line that it's having a problem with was changed to work with Blender 2.9.

If you can install HairNet 0.6.3 it should have the old line in place and may work better.
https://github.com/Jandals/HairNet/tree/v0.6.3

**Comment by meso1** [comment]
Works flawlessly. I figured a newer version of hairnet would be compatible with older versions of blender, my fault

**Comment by Jandals** [comment]
I'm glad it works. I'd like to maintain forward compatibility but I'm not that organized :)
