### ISSUE TITLE
Doesn't work in children interpolated mode.

### ISSUE THREAD

**Issue by fatboyzz** [Jandals/HairNet#44]
Using Blender 3.0.1 .
Hair particles generated from sheets.
Comp in particle edit.

Works fine in children simple mode.
![Simple](https://user-images.githubusercontent.com/1689443/154416619-42d00928-3c44-4308-8cd3-8f00c31945a1.PNG)

But wrong in children interpolated mode.
I added clump and seems in interpolated mode children snap to wrong parent.
![Interpolated](https://user-images.githubusercontent.com/1689443/154416705-1c398724-1a6a-408c-8806-ff7e8cb8a53f.PNG)

Testing file here
[HairNetTest.zip](https://github.com/Jandals/HairNet/files/8086054/HairNetTest.zip)

**Comment by Jandals** [comment]
That is a weird bug. And a new face of an old problem. There are some internal functions that HairNet may not have access to.
For now, the workaround is to click "Disconnect Hair" and then "Connect Hair" right afterwards. That seems to get it behaving properly for me without messing up anything else.

**Comment by fatboyzz** [comment]
Thanks for your reply. The reconnect method works for me.
