### ISSUE TITLE
blender 3.2 hairnet error

### ISSUE THREAD

**Issue by voluxgit** [Jandals/HairNet#49]
![image](https://user-images.githubusercontent.com/108188310/175784104-a58f205a-8fa9-44b7-b74c-5e6e2fa1ba30.png)
plz help me i am a beginner in blender and i am getting this error plz help

**Comment by martenzander** [comment]
having the same issue...

**Comment by Jandals** [comment]
It looks like there are some extra spaces in that brush instruction that are breaking it.

I'll try to post a correction later.

**Comment by martenzander** [comment]
That would be super cool. Just working on a project where HairNet would come in super handy.

**Comment by Jandals** [comment]
This error should be fixed in v0.6.7. There may be more, though…
https://github.com/Jandals/HairNet/releases/tag/v0.6.7

**Comment by martenzander** [comment]
Cool, gonna test it tonight. Thanks for the quick fix!
