### ISSUE TITLE
Won’t install

### ISSUE THREAD

**Issue by Peachypi** [Jandals/HairNet#6]
I just heard about your add on, and was really excited to try it, but it won’t install, every time I click the checkbox, it gives a trace back error

**Comment by Jandals** [comment]
Are you using the test version? I didn't make it clear that the most recent version available doesn't work with Blender.

This is the working version, and it requires Blender 2.79 (it doesn't work in 2.8 at this point)
https://github.com/Jandals/HairNet/releases/tag/v0.5.1

Sorry about the confusion
